public enum SabellaCatalogCoverage {
    public static let registeredTelevisionComponents: Set<String> = [
        "SabellaTVCard",
        "SabellaTVChannelGuide",
        "SabellaTVContextBadge",
        "SabellaTVEditorialRail",
        "SabellaTVHero",
        "SabellaTVNavigationBar",
        "SabellaTVPlaybackOverlay",
        "SabellaTVPrimaryButtonStyle",
        "SabellaTVScreen",
        "SabellaTVShelf",
    ]

    public static let registeredComponents: Set<String> = [
        "BleeckerAccordion",
        "BleeckerActivityItem",
        "BleeckerAlert",
        "BleeckerAdminShell",
        "BleeckerAppTabBar",
        "BleeckerAppShell",
        "BleeckerAvatar",
        "BleeckerBarChart",
        "BleeckerBauhausBackground",
        "BleeckerBrandLockup",
        "BleeckerBreadcrumb",
        "BleeckerButton",
        "BleeckerButtonGroup",
        "BleeckerButtonStyle",
        "BleeckerCard",
        "BleeckerCheckbox",
        "BleeckerCollectionFilters",
        "BleeckerCommandSpotlight",
        "BleeckerDashboardGrid",
        "BleeckerDashboardSection",
        "BleeckerDataList",
        "BleeckerDateRangePicker",
        "BleeckerDropdownMenu",
        "BleeckerEmptyState",
        "BleeckerErrorState",
        "BleeckerFeedItem",
        "BleeckerField",
        "BleeckerFileInput",
        "BleeckerFilterChip",
        "BleeckerFooter",
        "BleeckerHeader",
        "BleeckerHeroCarousel",
        "BleeckerIconBadge",
        "BleeckerIconButton",
        "BleeckerKbd",
        "BleeckerLineChart",
        "BleeckerLoadingOverlay",
        "BleeckerLoadingSpinner",
        "BleeckerMediaLibrary",
        "BleeckerMetric",
        "BleeckerMobileAppShell",
        "BleeckerModal",
        "BleeckerNotificationBadge",
        "BleeckerOTPInput",
        "BleeckerPageHeader",
        "BleeckerPagination",
        "BleeckerPanel",
        "BleeckerPanelLayout",
        "BleeckerPieChart",
        "BleeckerProgress",
        "BleeckerProgressStack",
        "BleeckerRadioGroup",
        "BleeckerScatterChart",
        "BleeckerSearchField",
        "BleeckerSectionHeader",
        "BleeckerSecureField",
        "BleeckerSegmentedControl",
        "BleeckerSelect",
        "BleeckerSeparator",
        "BleeckerSidebarItem",
        "BleeckerSkeleton",
        "BleeckerSlider",
        "BleeckerSparkline",
        "BleeckerStatCard",
        "BleeckerStatusBadge",
        "BleeckerStepper",
        "BleeckerSurfaceModifier",
        "BleeckerSwitchStyle",
        "BleeckerTabs",
        "BleeckerTextArea",
        "BleeckerTextField",
        "BleeckerTimelineItem",
        "BleeckerToggleStyle",
        "BleeckerTooltip",
    ]

    public static let platformExceptions: [String: Set<String>] = [
        "tvOS": ["BleeckerDateRangePicker", "BleeckerFileInput"],
    ]

    public static func missingComponents(
        publicComponents: Set<String>,
        registeredComponents: Set<String> = registeredComponents
    ) -> [String] {
        publicComponents.subtracting(registeredComponents).sorted()
    }

    public static func missingTelevisionComponents(publicComponents: Set<String>) -> [String] {
        publicComponents.subtracting(registeredTelevisionComponents).sorted()
    }
}
